spring:
  application:
    name: jpa-h2
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false
    #url: jdbc:h2:file:./h2/testdb;database_to_upper=false
    username: sa
    password: password
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default